version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: ⬆
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/lambdas/onboarding_event_handler"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/packages/driver_db"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/content_services/inspector"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: ⬆
