"""Action models for role->action policy mapping."""

import uuid

from sqlmodel import Field, SQLModel, UniqueConstraint

from ..models_enums import OrgRole, PrimaryAssetRole, TeamRole


class Action(SQLModel, table=True):
    """Defines an action that can be performed in the system."""

    key: str = Field(
        primary_key=True, description="Unique action key like 'codebase.generate_docs'"
    )
    description: str | None = Field(default=None)


# NOTE: ids on all RoleActionAllow* tables are NOT autogenerated, must be manually set at migration time to be a static value.
class RoleActionAllowAsset(SQLModel, table=True):
    """Maps asset roles to allowed actions for that asset type."""

    __tablename__ = "role_action_allow_asset"
    __table_args__ = (UniqueConstraint("role", "action_key", name="uq_allow_asset"),)

    id: uuid.UUID = Field(primary_key=True)
    role: PrimaryAssetRole = Field(index=True)
    action_key: str = Field(foreign_key="action.key", index=True)


class RoleActionAllowOrg(SQLModel, table=True):
    """Maps org roles to allowed actions at the org level."""

    __tablename__ = "role_action_allow_org"
    __table_args__ = (UniqueConstraint("role", "action_key", name="uq_allow_org"),)

    id: uuid.UUID = Field(primary_key=True)
    role: OrgRole = Field(index=True)
    action_key: str = Field(foreign_key="action.key", index=True)


class RoleActionAllowTeam(SQLModel, table=True):
    """Maps team roles to allowed actions at the team level."""

    __tablename__ = "role_action_allow_team"
    __table_args__ = (UniqueConstraint("role", "action_key", name="uq_allow_team"),)

    id: uuid.UUID = Field(primary_key=True)
    role: TeamRole = Field(index=True)
    action_key: str = Field(foreign_key="action.key", index=True)
