"""make org and user ids strings

Revision ID: 5cb5d4dd5fb6
Revises: c6744cecca4d
Create Date: 2024-05-09 12:21:46.960611

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cb5d4dd5fb6"
down_revision: str | None = "c6744cecca4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("codebases_creator_id_fkey", "codebases", type_="foreignkey")
    op.drop_constraint("users_organization_id_fkey", "users", type_="foreignkey")
    op.drop_constraint(
        "workspaces_organization_id_fkey", "workspaces", type_="foreignkey"
    )
    op.alter_column(
        "codebases",
        "creator_id",
        existing_type=sa.UUID(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=True,
    )

    op.alter_column(
        "users",
        "organization_id",
        existing_type=sa.UUID(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )

    op.alter_column(
        "workspaces",
        "organization_id",
        existing_type=sa.UUID(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE workspaces ALTER COLUMN organization_id TYPE uuid USING organization_id::uuid"
    )
    op.execute(
        "ALTER TABLE users ALTER COLUMN organization_id TYPE uuid USING organization_id::uuid"
    )
    op.execute(
        "ALTER TABLE codebases ALTER COLUMN creator_id TYPE uuid USING creator_id::uuid"
    )
    op.create_foreign_key(
        "workspaces_organization_id_fkey",
        "workspaces",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.create_foreign_key(
        "users_organization_id_fkey",
        "users",
        "organizations",
        ["organization_id"],
        ["id"],
    )
    op.create_foreign_key(
        "codebases_creator_id_fkey", "codebases", "users", ["creator_id"], ["id"]
    )

    # ### end Alembic commands ###
