"""add chunk indexes

Revision ID: ba2204f9ebda
Revises: d858e8f1ee5e
Create Date: 2024-08-06 13:57:24.872554

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "ba2204f9ebda"
down_revision = "d858e8f1ee5e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_chunk_content_metadata_id"),
        "chunk",
        ["content_metadata_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contentmetadata_content_type"),
        "contentmetadata",
        ["content_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contentmetadata_content_type"), table_name="contentmetadata")
    op.drop_index(op.f("ix_chunk_content_metadata_id"), table_name="chunk")
    # ### end Alembic commands ###
