"""derived content order addition

Revision ID: c6744cecca4d
Revises: b2feabbcc387
Create Date: 2024-04-17 14:06:37.132597

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6744cecca4d"
down_revision: str | None = "b2feabbcc387"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "derived_contents",
        sa.Column("order", sa.Integer(), server_default=sa.text("0"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("derived_contents", "order")
    # ### end Alembic commands ###
