"""Stragglers again

Revision ID: 093de2e6169a
Revises: cbd25d8d71ff
Create Date: 2024-07-25 13:55:02.711341

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "093de2e6169a"
down_revision = "cbd25d8d71ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_source_contents_codebase_id", table_name="source_contents")
    op.drop_index("ix_source_contents_workspace_id", table_name="source_contents")
    op.drop_table("source_contents")
    op.drop_table("source_content_types")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_content_types",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "type_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="source_content_types_pkey"),
        sa.UniqueConstraint("type_name", name="source_content_types_type_name_key"),
    )
    op.create_table(
        "source_contents",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("content_type_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("workspace_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("codebase_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("relative_path", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "order",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "generating",
                "generation-complete",
                "generation-error",
                name="enum_derived_content_status",
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["codebase_id"], ["codebases.id"], name="source_contents_codebase_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name="source_contents_workspace_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="source_contents_pkey"),
    )
    op.create_index(
        "ix_source_contents_workspace_id",
        "source_contents",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_source_contents_codebase_id",
        "source_contents",
        ["codebase_id"],
        unique=False,
    )
    # ### end Alembic commands ###
