"""adding created and updated at

Revision ID: 53972ce88dff
Revises: c2ec175264a8
Create Date: 2024-03-01 14:18:38.130201

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53972ce88dff"
down_revision: str | None = "c2ec175264a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunk", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "chunk", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "contentmetadata",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "contentmetadata",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "contentprocessingsession",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "contentprocessingsession",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contentprocessingsession", "updated_at")
    op.drop_column("contentprocessingsession", "created_at")
    op.drop_column("contentmetadata", "updated_at")
    op.drop_column("contentmetadata", "created_at")
    op.drop_column("chunk", "updated_at")
    op.drop_column("chunk", "created_at")
    # ### end Alembic commands ###
