"""add primary assets, versions, and nodes

Revision ID: 3ad0719e3e4c
Revises: 04593913d59f
Create Date: 2024-12-23 14:30:37.286656

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3ad0719e3e4c"
down_revision = "04593913d59f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "v2_primary_asset",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repository_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_v2_primary_asset_organization_id_display_name",
        "v2_primary_asset",
        ["organization_id", "display_name"],
        unique=True,
    )
    op.create_table(
        "v2_primary_asset_tag",
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("primary_asset_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["primary_asset_id"],
            ["v2_primary_asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("tag_id", "primary_asset_id"),
    )
    op.create_table(
        "v2_version",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("primary_asset_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("previous_version_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["previous_version_id"], ["v2_version.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["primary_asset_id"], ["v2_primary_asset.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_v2_version_primary_asset_id_display_name",
        "v2_version",
        ["primary_asset_id", "display_name"],
        unique=True,
    )
    op.create_table(
        "v2_node",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "CODEBASE_FILE",
                "CODEBASE_DIRECTORY",
                "OTHER",
                name="nodekind",
            ),
            nullable=False,
        ),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "misc_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["version_id"], ["v2_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_v2_node_relative_path"), "v2_node", ["relative_path"], unique=False
    )
    op.create_index(
        "ix_version_id_relative_path",
        "v2_node",
        ["version_id", "relative_path"],
        unique=True,
    )

    op.add_column("derived_contents", sa.Column("node_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_derived_contents_node_id"),
        "derived_contents",
        ["node_id"],
        unique=False,
    )
    op.create_foreign_key(None, "derived_contents", "v2_node", ["node_id"], ["id"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("derived_contents", "node_id")
    op.drop_index("ix_version_id_relative_path", table_name="v2_node")
    op.drop_index(op.f("ix_v2_node_relative_path"), table_name="v2_node")
    op.drop_table("v2_node")
    op.drop_index(
        "ix_v2_version_primary_asset_id_display_name", table_name="v2_version"
    )
    op.drop_table("v2_version")
    op.drop_table("v2_primary_asset_tag")
    op.drop_index(
        "ix_v2_primary_asset_organization_id_display_name",
        table_name="v2_primary_asset",
    )
    op.drop_table("v2_primary_asset")
    # ### end Alembic commands ###
