"""Add indexes

Revision ID: b133aee202aa
Revises: 1057562ffeae
Create Date: 2024-06-24 21:34:38.371609

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "b133aee202aa"
down_revision = "1057562ffeae"
branch_labels = None
depends_on = None


def upgrade():  # type: ignore
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_codebases_workspace_id"), "codebases", ["workspace_id"], unique=False
    )
    op.create_index(
        op.f("ix_derived_contents_source_content_id"),
        "derived_contents",
        ["source_content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derived_contents_derived_content_type_id"),
        "derived_contents",
        ["derived_content_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_contents_codebase_id"),
        "source_contents",
        ["codebase_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_contents_source_content_type_id"),
        "source_contents",
        ["source_content_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_contents_workspace_id"),
        "source_contents",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():  # type: ignore
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_contents_workspace_id"), table_name="source_contents")
    op.drop_index(
        op.f("ix_source_contents_source_content_type_id"), table_name="source_contents"
    )
    op.drop_index(op.f("ix_source_contents_codebase_id"), table_name="source_contents")
    op.drop_index(
        op.f("ix_derived_contents_source_content_id"), table_name="derived_contents"
    )
    op.drop_index(
        op.f("ix_derived_contents_derived_content_type_id"),
        table_name="derived_contents",
    )
    op.drop_index(op.f("ix_codebases_workspace_id"), table_name="codebases")
    # ### end Alembic commands ###
