"""Indices

Revision ID: 48d8020e043b
Revises: 093de2e6169a
Create Date: 2024-07-26 09:22:33.763687

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "48d8020e043b"
down_revision = "093de2e6169a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_derived_contents_codebase_id"),
        "derived_contents",
        ["codebase_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derived_contents_workspace_id"),
        "derived_contents",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_derived_contents_workspace_id"), table_name="derived_contents"
    )
    op.drop_index(
        op.f("ix_derived_contents_codebase_id"), table_name="derived_contents"
    )
    # ### end Alembic commands ###
