"""updated model

Revision ID: faa8d977ae43
Revises: d62236745250
Create Date: 2024-03-04 14:43:52.949374

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faa8d977ae43"
down_revision: str | None = "d62236745250"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunk", sa.Column("line_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunk", "line_number")
    # ### end Alembic commands ###
