"""add runtime logs

Revision ID: 77b384e95c97
Revises: 0d7d67c8730d
Create Date: 2024-03-28 16:19:09.857369

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "77b384e95c97"
down_revision: str | None = "0d7d67c8730d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtimelogagentinstance",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.types.Uuid(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codebase_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtimelogagenterror",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.types.Uuid(), nullable=False),
        sa.Column("agent_instance_id", sa.types.Uuid(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_instance_id"],
            ["runtimelogagentinstance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtimelogagentmessage",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.types.Uuid(), nullable=False),
        sa.Column("message", sa.JSON(), nullable=False),
        sa.Column("order", sa.Integer(), autoincrement=True, nullable=True),
        sa.Column("agent_instance_id", sa.types.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_instance_id"],
            ["runtimelogagentinstance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtimelogcontentretrieval",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.types.Uuid(), nullable=False),
        sa.Column("agent_instance_id", sa.types.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.types.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_instance_id"],
            ["runtimelogagentinstance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunk.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        "contentmetadata_content_processing_session_id_fkey",
        "contentmetadata",
        type_="foreignkey",
    )
    op.drop_column("contentmetadata", "content_processing_session_id")
    op.drop_table("contentprocessingsession")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contentmetadata",
        sa.Column(
            "content_processing_session_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
        ),
    )

    op.create_table(
        "contentprocessingsession",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("code_revision", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("arguments", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="contentprocessingsession_pkey"),
    )
    op.create_foreign_key(
        "contentmetadata_content_processing_session_id_fkey",
        "contentmetadata",
        "contentprocessingsession",
        ["content_processing_session_id"],
        ["id"],
    )
    op.drop_table("runtimelogcontentretrieval")
    op.drop_table("runtimelogagentmessage")
    op.drop_table("runtimelogagenterror")
    op.drop_table("runtimelogagentinstance")
    # ### end Alembic commands ###
