"""Add status to SC

Revision ID: edd6e7d6d98a
Revises: 6bf38bd239ab
Create Date: 2024-07-24 11:44:41.510528

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "edd6e7d6d98a"
down_revision = "6bf38bd239ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'derived_contents', 'workspaces', ['workspace_id'], ['id'])
    # op.create_foreign_key(None, 'derived_contents', 'codebases', ['codebase_id'], ['id'])
    op.add_column(
        "source_contents",
        sa.Column(
            "status",
            sa.Enum(
                "generating",
                "generation-complete",
                "generation-error",
                name="enum_derived_content_status",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_contents", "status")
    # op.drop_constraint(None, 'derived_contents', type_='foreignkey')
    # op.drop_constraint(None, 'derived_contents', type_='foreignkey')
    # ### end Alembic commands ###
