"""Add codebase_id to DerivedContent

Revision ID: 6bf38bd239ab
Revises: 5684bc66ddb3
Create Date: 2024-07-24 11:37:29.164793

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6bf38bd239ab"
down_revision = "5684bc66ddb3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "derived_contents",
        sa.Column("codebase_id", sa.types.Uuid(), nullable=True),
    )
    # op.create_foreign_key(None, 'derived_contents', 'workspaces', ['workspace_id'], ['id'])
    # op.create_foreign_key(None, 'derived_contents', 'codebases', ['codebase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'derived_contents', type_='foreignkey')
    # op.drop_constraint(None, 'derived_contents', type_='foreignkey')
    op.drop_column("derived_contents", "codebase_id")
    # ### end Alembic commands ###
