"""Add type to Tags

Revision ID: 55de8d497a29
Revises: 8cdbf2c4608d
Create Date: 2024-08-13 08:22:59.013335

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "55de8d497a29"
down_revision = "8cdbf2c4608d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("type", sa.String(length=255), nullable=True))
    op.execute("UPDATE tags SET type = 'tag'")
    op.alter_column("tags", "type", nullable=False)
    op.execute("CREATE INDEX IF NOT EXISTS ix_tag_type ON tags(type)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "type")
    # ### end Alembic commands ###
