"""Add git provider table

Revision ID: 86ed58d5305f
Revises: 78084f9c296b
Create Date: 2024-12-05 13:57:50.359714

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "86ed58d5305f"
down_revision = "78084f9c296b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_app_installations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "github_app_installation_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "github_app_installation_id",
            "organization_id",
            name="uq_github_app_installation_id_organization_id",
        ),
    )
    op.create_index(
        op.f("ix_github_app_installations_github_app_installation_id"),
        "github_app_installations",
        ["github_app_installation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_github_app_installations_organization_id"),
        "github_app_installations",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_github_app_installations_organization_id"),
        table_name="github_app_installations",
    )
    op.drop_index(
        op.f("ix_github_app_installations_github_app_installation_id"),
        table_name="github_app_installations",
    )
    op.drop_table("github_app_installations")
    # ### end Alembic commands ###
