"""Adds analysis_metadata to SourceContent

Revision ID: 1057562ffeae
Revises: 5cb5d4dd5fb6
Create Date: 2024-06-14 16:32:53.730949

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1057562ffeae"
down_revision = "5cb5d4dd5fb6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source_contents",
        sa.Column(
            "analysis_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_contents", "analysis_metadata")
    # ### end Alembic commands ###
