"""add previous_version_id index

Revision ID: 1475962b9869
Revises: 3605f4802da1
Create Date: 2024-12-12 13:49:27.361046

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1475962b9869"
down_revision = "3605f4802da1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index(
        op.f("ix_inspection_versions_previous_version_id"),
        "inspection_versions",
        ["previous_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_inspection_versions_previous_version_id"),
        table_name="inspection_versions",
    )
    # ### end Alembic commands ###
