"""Add document sources and includes

Revision ID: df374eaa585a
Revises: 55de8d497a29
Create Date: 2024-08-13 15:35:30.944708

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df374eaa585a"
down_revision = "55de8d497a29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_sources",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("include", sa.Boolean(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["derived_contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["derived_contents.id"],
        ),
        sa.PrimaryKeyConstraint("document_id", "source_id"),
    )
    op.add_column("tags_contents", sa.Column("include", sa.Boolean(), nullable=True))
    op.execute('UPDATE tags_contents SET "include" = true')
    op.alter_column("tags_contents", "include", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags_contents", "include")
    op.drop_table("document_sources")
    # ### end Alembic commands ###
