"""update derived_contents to use content_kind

Revision ID: fe3ae98dfbf6
Revises: 1475962b9869
Create Date: 2024-12-23 14:20:44.738378

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "fe3ae98dfbf6"
down_revision = "1475962b9869"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "derived_contents",
        sa.Column("content_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.execute("""
    UPDATE derived_contents
    SET content_kind = dc_type.type_name
    FROM derived_content_types dc_type
    WHERE derived_contents.content_type_id = dc_type.id;
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("derived_contents", "content_kind")
    # ### end Alembic commands ###
