"""Make DC status nullable for copying from SC

Revision ID: ccbc4d05e796
Revises: 85d10103ad3e
Create Date: 2024-07-24 14:04:36.945815

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ccbc4d05e796"
down_revision = "85d10103ad3e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "derived_contents",
        "status",
        existing_type=postgresql.ENUM(
            "generating",
            "generation-complete",
            "generation-error",
            name="enum_derived_content_status",
        ),
        nullable=True,
    )
    # op.create_foreign_key(None, 'derived_contents', 'codebases', ['codebase_id'], ['id'])
    # op.create_foreign_key(None, 'derived_contents', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'derived_contents', type_='foreignkey')
    # op.drop_constraint(None, 'derived_contents', type_='foreignkey')
    op.alter_column(
        "derived_contents",
        "status",
        existing_type=postgresql.ENUM(
            "generating",
            "generation-complete",
            "generation-error",
            name="enum_derived_content_status",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
