"""make workspace adn codebase nullable

Revision ID: 2641ed3d784a
Revises: 6e911298665b
Create Date: 2024-09-23 08:34:25.790970

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2641ed3d784a"
down_revision = "6e911298665b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "runtimelogagentinstance",
        "workspace_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "runtimelogagentinstance",
        "codebase_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    op.alter_column(
        "runtimelogagentinstance",
        "workspace_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "runtimelogagentinstance",
        "codebase_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
