"""Added tags and many to many mappings

Revision ID: fe4618de915c
Revises: 48d8020e043b
Create Date: 2024-07-31 11:57:52.469627

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "fe4618de915c"
down_revision = "48d8020e043b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("hex_color", sa.String(length=7), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "organization_id", name="unique_tag_name_per_org_id"
        ),
    )
    op.create_table(
        "tags_contents",
        sa.Column("tag_id", sa.types.Uuid(), nullable=False),
        sa.Column("content_id", sa.types.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["derived_contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("tag_id", "content_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_derived_contents_workspace_id"), table_name="derived_contents"
    )
    op.drop_index(
        op.f("ix_derived_contents_codebase_id"), table_name="derived_contents"
    )
    op.drop_table("tags_contents")
    op.drop_table("tags")
    # ### end Alembic commands ###
