"""disconnect derived_content version_id

Revision ID: 20b952b9cbe7
Revises: 3ad0719e3e4c
Create Date: 2024-12-23 14:56:35.453113

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "20b952b9cbe7"
down_revision = "3ad0719e3e4c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_derived_contents_version_id", table_name="derived_contents")
    op.drop_constraint(
        "derived_contents_version_id_fkey", "derived_contents", type_="foreignkey"
    )
    op.drop_index(
        "ix_inspection_versions_previous_version_id", table_name="inspection_versions"
    )
    op.drop_constraint(
        "inspection_versions_previous_version_id_fkey",
        "inspection_versions",
        type_="foreignkey",
    )
    op.execute("""
    UPDATE derived_contents
    SET version_id = codebase_id
    WHERE version_id IS NULL
    AND content_kind not in('supplemental-document', 'application_note', 'pdf-visual-summary', 'pdf-text-summary', 'pdf-image-summary', 'pdf-extracted-text', 'pdf-extracted-table', 'pdf_summary');
    """)
    op.execute("""
    UPDATE derived_contents
    SET version_id = source_content_id
    WHERE version_id IS NULL;
    """)
    op.execute("""
    UPDATE derived_contents
    SET version_id = id
    WHERE version_id IS NULL;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    UPDATE derived_contents
    SET version_id = NULL
    WHERE version_id = codebase_id;
    """)
    op.execute("""
    UPDATE derived_contents
    SET version_id = NULL
    WHERE version_id = source_content_id;
    """)
    op.execute("""
    UPDATE derived_contents
    SET version_id = NULL
    WHERE version_id = id;
    """)
    op.create_foreign_key(
        "derived_contents_version_id_fkey",
        "derived_content",
        "inspection_versions",
        ["version_id"],
        ["id"],
    )
    op.create_index(
        "ix_derived_contents_version_id",
        "derived_contents",
        ["version_id"],
        unique=False,
    )
    op.create_foreign_key(
        "inspection_versions_previous_version_id_fkey",
        "inspection_versions",
        "inspection_versions",
        ["previous_version_id"],
        ["id"],
    )
    op.create_index(
        "ix_inspection_versions_previous_version_id",
        "inspection_versions",
        ["previous_version_id"],
        unique=False,
    )


# ### end Alembic commands ###
