"""make content_kind non-nullable

Revision ID: 04593913d59f
Revises: fe3ae98dfbf6
Create Date: 2024-12-23 14:28:03.448879

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04593913d59f"
down_revision = "fe3ae98dfbf6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "derived_contents",
        "content_kind",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_derived_contents_content_kind"),
        "derived_contents",
        ["content_kind"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_derived_contents_content_kind"), table_name="derived_contents"
    )
    op.alter_column(
        "derived_contents",
        "content_kind",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
