"""Add usage subscription tables

Revision ID: 3605f4802da1
Revises: 86ed58d5305f
Create Date: 2024-12-11 15:54:28.422354

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "3605f4802da1"
down_revision = "86ed58d5305f"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "subscription",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "plan_type",
            sa.Enum("CORE", "ADVANCED", "ENTERPRISE", name="plantype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CANCELED", "SUSPENDED", name="subscriptionstatus"),
            nullable=False,
        ),
        sa.Column(
            "billing_frequency",
            sa.Enum("MONTHLY", "ANNUAL", name="billingfrequency"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_organization_id"),
        "subscription",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_plan_type"), "subscription", ["plan_type"], unique=False
    )
    op.create_index(
        "unique_active_subscription_per_org",
        "subscription",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_active_subscription_per_org",
        table_name="subscription",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(op.f("ix_subscription_plan_type"), table_name="subscription")
    op.drop_index(op.f("ix_subscription_organization_id"), table_name="subscription")
    op.drop_table("subscription")
    op.execute("DROP TYPE IF EXISTS plantype")
    op.execute("DROP TYPE IF EXISTS subscriptionstatus")
    op.execute("DROP TYPE IF EXISTS billingfrequency")

    # ### end Alembic commands ###
