"""Make sc id on DC nullable in prep for copy

Revision ID: 85d10103ad3e
Revises: edd6e7d6d98a
Create Date: 2024-07-24 12:20:29.119688

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "85d10103ad3e"
down_revision = "edd6e7d6d98a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "derived_contents", "source_content_id", existing_type=sa.UUID(), nullable=True
    )
    # op.create_foreign_key(None, 'derived_contents', 'codebases', ['codebase_id'], ['id'])
    # op.create_foreign_key(None, 'derived_contents', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index("ix_source_contents_content_type_id", table_name="source_contents")
    op.drop_constraint(
        "source_contents_source_content_type_id_fkey",
        "source_contents",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "source_contents_source_content_type_id_fkey",
        "source_contents",
        "source_content_types",
        ["content_type_id"],
        ["id"],
    )
    op.create_index(
        "ix_source_contents_content_type_id",
        "source_contents",
        ["content_type_id"],
        unique=False,
    )
    # op.drop_constraint(None, 'derived_contents', type_='foreignkey')
    # op.drop_constraint(None, 'derived_contents', type_='foreignkey')
    op.alter_column(
        "derived_contents", "source_content_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
