"""New embedding model

Revision ID: 2f79ea9294a7
Revises: 95c5d718968c
Create Date: 2024-08-13 09:55:44.472693

"""

import pgvector
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f79ea9294a7"
down_revision = "95c5d718968c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunkandembedding",
        sa.Column("id", sa.types.Uuid(), nullable=False),
        sa.Column("content_id", sa.types.Uuid(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "text_embedding_3_small",
            pgvector.sqlalchemy.Vector(dim=1536),
            nullable=True,
        ),
        sa.Column("chunk_number", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["derived_contents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("setup_completed")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "setup_completed",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="setup_completed_pkey"),
    )
    op.drop_table("chunkandembedding")
    # ### end Alembic commands ###
