"""Add indexes

Revision ID: 8cdbf2c4608d
Revises: 37da9f662cf0
Create Date: 2024-08-20 17:31:09.673164

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8cdbf2c4608d"
down_revision = "37da9f662cf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_chunkandembedding_content_id"),
        "chunkandembedding",
        ["content_id"],
        unique=False,
    )
    op.drop_constraint(
        "chunkandembedding_content_id_fkey", "chunkandembedding", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "chunkandembedding",
        "derived_contents",
        ["content_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_derived_contents_content_type_id"),
        "derived_contents",
        ["content_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_derived_contents_relative_path"),
        "derived_contents",
        ["relative_path"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_derived_contents_relative_path"), table_name="derived_contents"
    )
    op.drop_index(
        op.f("ix_derived_contents_content_type_id"), table_name="derived_contents"
    )
    op.drop_constraint(None, "chunkandembedding", type_="foreignkey")
    op.create_foreign_key(
        "chunkandembedding_content_id_fkey",
        "chunkandembedding",
        "derived_contents",
        ["content_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_chunkandembedding_content_id"), table_name="chunkandembedding"
    )
    # ### end Alembic commands ###
