"""Stragglers

Revision ID: 9ce7977fdcb5
Revises: 9fdb9475d8f4
Create Date: 2024-07-24 16:22:43.886518

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "9ce7977fdcb5"
down_revision = "9fdb9475d8f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_source_contents_codebase_id', table_name='source_contents')
    # op.drop_index('ix_source_contents_workspace_id', table_name='source_contents')
    # op.drop_table('source_contents')
    # op.drop_table('source_content_types')
    op.drop_constraint(
        "derived_contents_source_content_id_fkey",
        "derived_contents",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "derived_contents", "derived_contents", ["source_content_id"], ["id"]
    )
    op.create_foreign_key(
        None, "derived_contents", "codebases", ["codebase_id"], ["id"]
    )
    op.create_foreign_key(
        None, "derived_contents", "workspaces", ["workspace_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
