"""Update InspectorRun to cascade delete. Drops inspection_version_id column

Revision ID: 3b2cb97a373b
Revises: 6144fad19eae
Create Date: 2025-02-05 16:16:38.786879

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3b2cb97a373b"
down_revision = "6144fad19eae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM inspectorrun WHERE version_id IS NULL")
    op.alter_column(
        "inspectorrun", "version_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_constraint(
        "inspectorrun_version_id_fkey", "inspectorrun", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "inspectorrun", "v2_version", ["version_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("inspectorrun", "inspection_version_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inspectorrun",
        sa.Column(
            "inspection_version_id", sa.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "inspectorrun", type_="foreignkey")
    op.create_foreign_key(
        "inspectorrun_version_id_fkey",
        "inspectorrun",
        "v2_version",
        ["version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "inspectorrun", "version_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
