"""add bitbucket gitproviderkinds

Revision ID: 0d8a28ac87e5
Revises: 6d7b7fe63930
Create Date: 2025-07-15 14:46:02.043087

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0d8a28ac87e5"
down_revision = "d3db21ab0782"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "git_provider_apps",
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###
    op.execute("ALTER TYPE gitproviderkind ADD VALUE 'BITBUCKET'")
    op.execute("ALTER TYPE gitproviderkind ADD VALUE 'BITBUCKET_DATA_CENTER'")
    op.execute("ALTER TYPE gitproviderkind ADD VALUE 'BITBUCKET_SERVER'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("git_provider_apps", "metadata")
    # ### end Alembic commands ###
