"""cascade tag deletion

Revision ID: a372b5f57109
Revises: 57be28321d1c
Create Date: 2025-01-14 10:00:02.124561

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "a372b5f57109"
down_revision = "57be28321d1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        "v2_primary_asset_tag_primary_asset_id_fkey",
        "v2_primary_asset_tag",
        type_="foreignkey",
    )
    op.drop_constraint(
        "v2_primary_asset_tag_tag_id_fkey", "v2_primary_asset_tag", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "v2_primary_asset_tag", "tags", ["tag_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "v2_primary_asset_tag",
        "v2_primary_asset",
        ["primary_asset_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "v2_primary_asset_tag", type_="foreignkey")
    op.drop_constraint(None, "v2_primary_asset_tag", type_="foreignkey")
    op.create_foreign_key(
        "v2_primary_asset_tag_tag_id_fkey",
        "v2_primary_asset_tag",
        "tags",
        ["tag_id"],
        ["id"],
    )
    op.create_foreign_key(
        "v2_primary_asset_tag_primary_asset_id_fkey",
        "v2_primary_asset_tag",
        "v2_primary_asset",
        ["primary_asset_id"],
        ["id"],
    )
    # ### end Alembic commands ###
