"""add_api_key.last_used_at

Revision ID: 4902391a31a8
Revises: 0d8a28ac87e5
Create Date: 2025-08-11 12:13:34.439862

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4902391a31a8"
down_revision = "0d8a28ac87e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("v2_api_key", sa.Column("last_used_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("v2_api_key", "last_used_at")
    # ### end Alembic commands ###
