"""node depth

Revision ID: 47fbcf862323
Revises: b1466ca58da1
Create Date: 2025-03-12 11:10:14.135578

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "47fbcf862323"
down_revision = "b1466ca58da1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "v2_node",
        sa.Column(
            "depth",
            sa.Integer(),
            sa.Computed(
                "length(trim(trailing '/' from relative_path)) - length(replace(trim(trailing '/' from relative_path), '/', ''))",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_v2_node_depth"), "v2_node", ["depth"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_v2_node_depth"), table_name="v2_node")
    op.drop_column("v2_node", "depth")
    # ### end Alembic commands ###
