"""adds actions, teams, and acl tables

Revision ID: 4060b23411c9
Revises: 2071d63ae34b
Create Date: 2025-10-15 13:03:01.657323

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4060b23411c9"
down_revision = "2071d63ae34b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "role_action_allow_asset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("admin", "viewer", name="primaryassetrole"), nullable=False
        ),
        sa.Column("action_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_key"],
            ["action.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role", "action_key", name="uq_allow_asset"),
    )
    op.create_index(
        op.f("ix_role_action_allow_asset_action_key"),
        "role_action_allow_asset",
        ["action_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_action_allow_asset_role"),
        "role_action_allow_asset",
        ["role"],
        unique=False,
    )
    role_enum = postgresql.ENUM(
        "super_admin", "member", name="orgrole", create_type=False
    )
    op.create_table(
        "role_action_allow_org",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("role", role_enum, nullable=False),
        sa.Column("action_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_key"],
            ["action.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role", "action_key", name="uq_allow_org"),
    )
    op.create_index(
        op.f("ix_role_action_allow_org_action_key"),
        "role_action_allow_org",
        ["action_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_action_allow_org_role"),
        "role_action_allow_org",
        ["role"],
        unique=False,
    )
    op.create_table(
        "role_action_allow_team",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("team_admin", "member", name="teamrole"), nullable=False
        ),
        sa.Column("action_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_key"],
            ["action.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role", "action_key", name="uq_allow_team"),
    )
    op.create_index(
        op.f("ix_role_action_allow_team_action_key"),
        "role_action_allow_team",
        ["action_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_action_allow_team_role"),
        "role_action_allow_team",
        ["role"],
        unique=False,
    )
    op.create_table(
        "team",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_team_org_name"),
    )
    op.create_index(
        op.f("ix_team_organization_id"), "team", ["organization_id"], unique=False
    )
    op.create_table(
        "team_membership",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "role", sa.Enum("team_admin", "member", name="teamrole"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "user_id", name="uq_team_member"),
    )
    op.create_index(
        op.f("ix_team_membership_team_id"), "team_membership", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_team_membership_user_id"), "team_membership", ["user_id"], unique=False
    )
    op.create_table(
        "primary_asset_role_grant",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("primary_asset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "principal_kind",
            sa.Enum("user", "team", "org", "public", name="principalkind"),
            nullable=False,
        ),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column(
            "role", sa.Enum("admin", "viewer", name="primaryassetrole"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            (principal_kind = 'user'   AND user_id IS NOT NULL AND team_id IS NULL) OR\n            (principal_kind = 'team'   AND team_id IS NOT NULL AND user_id IS NULL) OR\n            (principal_kind = 'org'    AND user_id IS NULL    AND team_id IS NULL) OR\n            (principal_kind = 'public' AND user_id IS NULL    AND team_id IS NULL)\n            ",
            name="chk_exactly_one_principal",
        ),
        sa.CheckConstraint(
            "principal_kind NOT IN ('org','public') OR role = 'viewer'",
            name="chk_org_public_view_only",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["primary_asset_id"],
            ["primary_asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_primary_asset_role_grant_organization_id"),
        "primary_asset_role_grant",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_primary_asset_role_grant_primary_asset_id"),
        "primary_asset_role_grant",
        ["primary_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_primary_asset_role_grant_team_id"),
        "primary_asset_role_grant",
        ["team_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_primary_asset_role_grant_user_id"),
        "primary_asset_role_grant",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_parg_orgwide",
        "primary_asset_role_grant",
        ["primary_asset_id"],
        unique=True,
        postgresql_where=sa.text("principal_kind = 'org'"),
    )
    op.create_index(
        "uq_parg_public",
        "primary_asset_role_grant",
        ["primary_asset_id"],
        unique=True,
        postgresql_where=sa.text("principal_kind = 'public'"),
    )
    op.create_index(
        "uq_parg_team",
        "primary_asset_role_grant",
        ["primary_asset_id", "team_id"],
        unique=True,
        postgresql_where=sa.text("team_id IS NOT NULL"),
    )
    op.create_index(
        "uq_parg_user",
        "primary_asset_role_grant",
        ["primary_asset_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_parg_user",
        table_name="primary_asset_role_grant",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_parg_team",
        table_name="primary_asset_role_grant",
        postgresql_where=sa.text("team_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_parg_public",
        table_name="primary_asset_role_grant",
        postgresql_where=sa.text("principal_kind = 'public'"),
    )
    op.drop_index(
        "uq_parg_orgwide",
        table_name="primary_asset_role_grant",
        postgresql_where=sa.text("principal_kind = 'org'"),
    )
    op.drop_index(
        op.f("ix_primary_asset_role_grant_user_id"),
        table_name="primary_asset_role_grant",
    )
    op.drop_index(
        op.f("ix_primary_asset_role_grant_team_id"),
        table_name="primary_asset_role_grant",
    )
    op.drop_index(
        op.f("ix_primary_asset_role_grant_primary_asset_id"),
        table_name="primary_asset_role_grant",
    )
    op.drop_index(
        op.f("ix_primary_asset_role_grant_organization_id"),
        table_name="primary_asset_role_grant",
    )
    op.drop_table("primary_asset_role_grant")
    op.drop_index(op.f("ix_team_membership_user_id"), table_name="team_membership")
    op.drop_index(op.f("ix_team_membership_team_id"), table_name="team_membership")
    op.drop_table("team_membership")
    op.drop_index(op.f("ix_team_organization_id"), table_name="team")
    op.drop_table("team")
    op.drop_index(
        op.f("ix_role_action_allow_team_role"), table_name="role_action_allow_team"
    )
    op.drop_index(
        op.f("ix_role_action_allow_team_action_key"),
        table_name="role_action_allow_team",
    )
    op.drop_table("role_action_allow_team")
    op.drop_index(
        op.f("ix_role_action_allow_org_role"), table_name="role_action_allow_org"
    )
    op.drop_index(
        op.f("ix_role_action_allow_org_action_key"), table_name="role_action_allow_org"
    )
    op.drop_table("role_action_allow_org")
    op.drop_index(
        op.f("ix_role_action_allow_asset_role"), table_name="role_action_allow_asset"
    )
    op.drop_index(
        op.f("ix_role_action_allow_asset_action_key"),
        table_name="role_action_allow_asset",
    )
    op.drop_table("role_action_allow_asset")
    op.drop_table("action")
    # ### end Alembic commands ###
