"""Create UserCache and VersionCreator tables

Revision ID: bf955986b171
Revises: 2c5d9d6cbdb5
Create Date: 2025-03-05 10:09:02.066745

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf955986b171"
down_revision = "2c5d9d6cbdb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_cache",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "version_creator",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_cache.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["version_id"], ["v2_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("version_id"),
    )
    op.create_index(
        op.f("ix_version_creator_user_id"), "version_creator", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_version_creator_version_id"),
        "version_creator",
        ["version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_version_creator_version_id"), table_name="version_creator")
    op.drop_index(op.f("ix_version_creator_user_id"), table_name="version_creator")
    op.drop_table("version_creator")
    op.drop_table("user_cache")
    # ### end Alembic commands ###
