"""document_source pk reset

Revision ID: 57be28321d1c
Revises: 950be3322d45
Create Date: 2025-01-08 11:55:58.721867

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "57be28321d1c"
down_revision = "950be3322d45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM document_sources
        WHERE source_node_id IS NULL OR page_node_id IS NULL
        """
    )
    op.execute(
        """
        DELETE FROM document_sources
        WHERE (source_node_id, page_node_id) IN (
            SELECT source_node_id, page_node_id
            FROM document_sources
            GROUP BY source_node_id, page_node_id
            HAVING COUNT(*) > 1
        )
        """
    )
    op.drop_constraint("document_sources_pkey", "document_sources", type_="primary")
    op.create_primary_key(
        "document_sources_pkey", "document_sources", ["source_node_id", "page_node_id"]
    )
    op.alter_column(
        "document_sources", "document_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "document_sources", "include", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "document_sources", "source_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "document_sources", "source_node_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "document_sources", "page_node_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "document_sources", "page_node_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "document_sources", "source_node_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "document_sources", "source_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "document_sources", "include", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "document_sources", "document_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
