"""add_azure_devops_provider_support

Revision ID: c91cd18687a1
Revises: 3f73cfc851d9
Create Date: 2025-09-16 18:23:50.337178

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c91cd18687a1"
down_revision = "ef070600b9dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add Azure DevOps to GitProviderKind enum
    op.execute("ALTER TYPE gitproviderkind ADD VALUE 'AZURE_DEVOPS_CLOUD'")
    op.execute("ALTER TYPE primaryassetprovider ADD VALUE 'AZURE_DEVOPS_CLOUD'")


def downgrade() -> None:
    pass
