"""Adds vcs_hash, vcs_metadata to version, source_provider to primary asset, and new enum values

Revision ID: e92af25eccc5
Revises: 6d7b7fe63930
Create Date: 2025-07-16 12:51:54.108140

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e92af25eccc5"
down_revision = "6d7b7fe63930"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # create the primaryassetprovider type
    primaryassetprovider = sa.Enum(
        "GITHUB",
        "GITLAB_SELF_MANAGED",
        "BITBUCKET",
        "USER",
        name="primaryassetprovider",
    )
    # bind the type to the current connection
    primaryassetprovider.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "v2_primary_asset", sa.Column("provider", primaryassetprovider, nullable=True)
    )
    op.create_index(
        op.f("ix_v2_primary_asset_provider"),
        "v2_primary_asset",
        ["provider"],
        unique=False,
    )
    op.add_column(
        "v2_version",
        sa.Column("vcs_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "v2_version",
        sa.Column(
            "vcs_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###
    op.execute("ALTER TYPE contentkind ADD VALUE 'CODEBASE_AUDIENCES'")
    op.execute("ALTER TYPE contentkind ADD VALUE 'CODEBASE_DOMAINS'")
    op.execute("ALTER TYPE contentkind ADD VALUE 'CODEBASE_KINDS'")
    op.execute("ALTER TYPE contentkind ADD VALUE 'CODEBASE_ENTRY_POINTS'")
    # for PrimaryAssetKind in {FILE, PAGE, PAGE_TEMPLATE}: set to USER
    op.execute(
        "UPDATE v2_primary_asset SET provider = 'USER' WHERE kind IN ('FILE', 'PAGE', 'PAGE_TEMPLATE')"
    )
    # for PrimaryAssetKind in {CODEBASE}: logic to figure out USER, GITHUB or GITLAB_SELF_MANAGED
    # three cases: repository_id and installation_id are both null -> USER
    # repository_id is not null and installation_id is null -> GITHUB
    # repository_id is not null and installation_id is not null -> GITLAB_SELF_MANAGED
    op.execute("""
        UPDATE v2_primary_asset
        SET provider = CASE
            WHEN repository_id IS NULL AND installation_id IS NULL THEN 'USER'::primaryassetprovider
            WHEN repository_id IS NOT NULL AND installation_id IS NULL THEN 'GITHUB'::primaryassetprovider
            WHEN repository_id IS NOT NULL AND installation_id IS NOT NULL THEN 'GITLAB_SELF_MANAGED'::primaryassetprovider
        END
        WHERE kind = 'CODEBASE'
    """)
    # if primary_asset.provider != 'USER' then vcs_hash = display_name
    op.execute("""
        UPDATE v2_version
        SET vcs_hash = v2_version.display_name
        FROM v2_primary_asset
        WHERE v2_version.primary_asset_id = v2_primary_asset.id
        AND v2_primary_asset.provider != 'USER'
    """)
    # NOTE: vcs_metadata is not backfilled here
    # make the provider column non-nullable
    op.alter_column(
        "v2_primary_asset",
        "provider",
        existing_type=sa.Enum(
            "GITHUB",
            "GITLAB_SELF_MANAGED",
            "BITBUCKET",
            "USER",
            name="primaryassetprovider",
        ),
        nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("v2_version", "vcs_metadata")
    op.drop_column("v2_version", "vcs_hash")
    op.drop_index(op.f("ix_v2_primary_asset_provider"), table_name="v2_primary_asset")
    op.drop_column("v2_primary_asset", "provider")
    # ### end Alembic commands ###
    op.execute("ALTER TYPE contentkind DROP VALUE 'CODEBASE_AUDIENCES'")
    op.execute("ALTER TYPE contentkind DROP VALUE 'CODEBASE_DOMAINS'")
    op.execute("ALTER TYPE contentkind DROP VALUE 'CODEBASE_KINDS'")
    op.execute("ALTER TYPE contentkind DROP VALUE 'CODEBASE_ENTRY_POINTS'")
