"""update primary asset table

Revision ID: a9eb69a99830
Revises: e636d17e65dd
Create Date: 2025-02-12 16:04:59.671260

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a9eb69a99830"
down_revision = "e636d17e65dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "v2_primary_asset", sa.Column("installation_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "v2_primary_asset",
        "git_provider_app_installations",
        ["installation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "v2_primary_asset", type_="foreignkey")
    op.drop_column("v2_primary_asset", "installation_id")
    # ### end Alembic commands ###
