"""capture missing changes from models

Revision ID: 746ab52e9211
Revises: dfeeb5035f6f
Create Date: 2025-01-02 10:02:38.374493

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "746ab52e9211"
down_revision = "dfeeb5035f6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('chunkandembedding_content_id_fkey', 'chunkandembedding', type_='foreignkey')
    # op.create_foreign_key(None, 'chunkandembedding', 'derived_contents', ['content_id'], ['id'])

    op.alter_column(
        "derived_contents", "workspace_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "derived_contents", "content_type_id", existing_type=sa.UUID(), nullable=True
    )

    # op.drop_index('derived_contents_metadata_idx', table_name='derived_contents', postgresql_using='gin')
    # op.drop_index('ix_derived_contents_codebase_id', table_name='derived_contents')
    # op.drop_index('ix_derived_contents_content_name', table_name='derived_contents')
    # op.drop_index('ix_derived_contents_content_type_id', table_name='derived_contents')
    # op.drop_index('ix_derived_contents_source_content_id', table_name='derived_contents')
    # op.drop_index('ix_derived_contents_workspace_id', table_name='derived_contents')
    op.drop_constraint(
        "derived_contents_codebase_id_fkey", "derived_contents", type_="foreignkey"
    )
    op.drop_constraint(
        "derived_contents_derived_content_type_id_fkey",
        "derived_contents",
        type_="foreignkey",
    )
    op.drop_constraint(
        "derived_contents_source_content_id_fkey",
        "derived_contents",
        type_="foreignkey",
    )
    op.drop_constraint(
        "derived_contents_workspace_id_fkey", "derived_contents", type_="foreignkey"
    )
    # op.drop_index('ix_tag_type', table_name='tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
