"""Add git_provider tables

Revision ID: 6144fad19eae
Revises: 451bf2d9113c
Create Date: 2025-01-28 12:54:01.907797

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "6144fad19eae"
down_revision = "451bf2d9113c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "git_provider_apps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider_kind",
            sa.Enum("GITLAB", "GITLAB_ENTERPRISE_SELF_MANAGED", name="gitproviderkind"),
            nullable=False,
        ),
        sa.Column("shared_provider", sa.Boolean(), nullable=False),
        sa.Column(
            "owner_organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("redirect_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scopes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_git_provider_apps_client_id"),
        "git_provider_apps",
        ["client_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_git_provider_apps_owner_organization_id"),
        "git_provider_apps",
        ["owner_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_git_provider_apps_provider_kind"),
        "git_provider_apps",
        ["provider_kind"],
        unique=False,
    )
    op.create_table(
        "git_provider_app_installations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("git_provider_app_id", sa.Uuid(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["git_provider_app_id"], ["git_provider_apps.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "git_provider_app_id",
            "organization_id",
            "user_id",
            name="uq_git_provider_app_id_organization_id_user_id",
        ),
    )
    op.create_index(
        op.f("ix_git_provider_app_installations_git_provider_app_id"),
        "git_provider_app_installations",
        ["git_provider_app_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_git_provider_app_installations_git_provider_app_id"),
        table_name="git_provider_app_installations",
    )
    op.drop_table("git_provider_app_installations")
    op.drop_index(
        op.f("ix_git_provider_apps_provider_kind"), table_name="git_provider_apps"
    )
    op.drop_index(
        op.f("ix_git_provider_apps_owner_organization_id"),
        table_name="git_provider_apps",
    )
    op.drop_index(
        op.f("ix_git_provider_apps_client_id"), table_name="git_provider_apps"
    )
    op.drop_table("git_provider_apps")
    op.execute("DROP TYPE IF EXISTS gitproviderkind")

    # ### end Alembic commands ###
