"""Adds call_id to InspectorRun

Revision ID: 830fe3c26803
Revises: 61e839b3f9cd
Create Date: 2025-05-14 16:14:46.502925

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "830fe3c26803"
down_revision = "20a68960f41f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inspectorrun",
        sa.Column("call_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inspectorrun", "call_id")
    # ### end Alembic commands ###
