"""cascade source and derived content deletion

Revision ID: cd839fe094c1
Revises: a372b5f57109
Create Date: 2025-01-14 10:03:39.760149

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "cd839fe094c1"
down_revision = "a372b5f57109"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "derived_contents_node_id_fkey", "derived_contents", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "derived_contents", "v2_node", ["node_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "document_sources_page_node_id_fkey", "document_sources", type_="foreignkey"
    )
    op.drop_constraint(
        "document_sources_source_node_id_fkey", "document_sources", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "document_sources",
        "v2_node",
        ["page_node_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "document_sources",
        "v2_node",
        ["source_node_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "document_sources", type_="foreignkey")
    op.drop_constraint(None, "document_sources", type_="foreignkey")
    op.create_foreign_key(
        "document_sources_source_node_id_fkey",
        "document_sources",
        "v2_node",
        ["source_node_id"],
        ["id"],
    )
    op.create_foreign_key(
        "document_sources_page_node_id_fkey",
        "document_sources",
        "v2_node",
        ["page_node_id"],
        ["id"],
    )
    op.drop_constraint(None, "derived_contents", type_="foreignkey")
    op.create_foreign_key(
        "derived_contents_node_id_fkey",
        "derived_contents",
        "v2_node",
        ["node_id"],
        ["id"],
    )
    # ### end Alembic commands ###
