"""add node total_files

Revision ID: 21e1da60676a
Revises: c852fcd10a2f
Create Date: 2025-04-07 11:40:48.665443

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21e1da60676a"
down_revision = "c852fcd10a2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "v2_node",
        sa.Column(
            "total_files",
            sa.Integer(),
            sa.Computed("(misc_metadata->>'total_files')::INTEGER", persisted=True),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_v2_node_total_files"), "v2_node", ["total_files"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_v2_node_total_files"), table_name="v2_node")
    op.drop_column("v2_node", "total_files")
    # ### end Alembic commands ###
