"""codebase_settings_auto_commit_docs

Revision ID: 00db4f3a9545
Revises: 61e839b3f9cd
Create Date: 2025-05-15 10:50:43.203323

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "00db4f3a9545"
down_revision = "830fe3c26803"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "v2_primary_asset",
        sa.Column("codebase_settings_auto_commit_docs", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###
    # Set default value for existing rows to False when kind = CODEBASE
    op.execute(
        """
        UPDATE v2_primary_asset
        SET codebase_settings_auto_commit_docs = FALSE
        WHERE kind = 'CODEBASE'
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("v2_primary_asset", "codebase_settings_auto_commit_docs")
    # ### end Alembic commands ###
