"""content_type_id and version_id and content_name

Revision ID: 25d3fa4abdc5
Revises: c658bca65e0c
Create Date: 2025-01-17 14:10:22.379122

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "25d3fa4abdc5"
down_revision = "c658bca65e0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("derived_contents", "source_content_id")
    op.drop_column("derived_contents", "version_id")
    op.drop_column("derived_contents", "content_type_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "derived_contents",
        sa.Column("content_type_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "derived_contents",
        sa.Column("version_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "derived_contents",
        sa.Column("source_content_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
