"""adds vcs_tracked_branch to PrimaryAsset to allow for non-default branch tracking

Revision ID: ef070600b9dd
Revises: 3f73cfc851d9
Create Date: 2025-09-16 16:45:48.822904

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef070600b9dd"
down_revision = "3f73cfc851d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "primary_asset",
        sa.Column(
            "vcs_tracked_branch", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("primary_asset", "vcs_tracked_branch")
    # ### end Alembic commands ###
