"""add insufficient balance to version status enum

Revision ID: 20a68960f41f
Revises: 61e839b3f9cd
Create Date: 2025-05-14 19:55:51.535346

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "20a68960f41f"
down_revision = "61e839b3f9cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE versionstatus ADD VALUE 'INSUFFICIENT_BALANCE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
