"""adds VersionNode table and associated changes

Revision ID: 83650d298b58
Revises: a03d3f6c9793
Create Date: 2025-12-14 00:00:00.000000

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "83650d298b58"
down_revision = "a03d3f6c9793"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "version_node",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column(
            "depth",
            sa.Integer(),
            sa.Computed(
                "length(trim(trailing '/' from relative_path)) - length(replace(trim(trailing '/' from relative_path), '/', ''))",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "total_files",
            sa.Integer(),
            sa.Computed(
                "(misc_metadata->>'total_files')::INTEGER",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "misc_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(["version_id"], ["version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "version_id",
            "relative_path",
            name="ix_version_node_version_id_relative_path",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_version_node_depth"), "version_node", ["depth"], unique=False
    )
    op.create_index(
        op.f("ix_version_node_relative_path"),
        "version_node",
        ["relative_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_version_node_version_id"), "version_node", ["version_id"], unique=False
    )

    op.add_column("document_source", sa.Column("id", sa.Uuid(), nullable=True))
    op.execute("UPDATE document_source SET id = gen_random_uuid()")
    op.alter_column("document_source", "id", nullable=False)
    op.drop_constraint("document_sources_pkey", "document_source", type_="primary")
    op.create_primary_key("document_sources_pkey", "document_source", ["id"])

    op.add_column(
        "document_source", sa.Column("source_version_node_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "document_source", sa.Column("page_version_node_id", sa.Uuid(), nullable=True)
    )
    op.alter_column(
        "document_source", "source_node_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "document_source", "page_node_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        "document_sources_source_node_id_fkey", "document_source", type_="foreignkey"
    )
    op.drop_constraint(
        "document_sources_page_node_id_fkey", "document_source", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "document_source", "node", ["source_node_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None,
        "document_source",
        "version_node",
        ["page_version_node_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "document_source",
        "version_node",
        ["source_version_node_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "document_source", "node", ["page_node_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "node",
        sa.Column("source_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("node", sa.Column("primary_asset_id", sa.Uuid(), nullable=True))
    op.drop_index("ix_version_id_relative_path", table_name="node")
    op.create_index(
        op.f("ix_node_primary_asset_id"), "node", ["primary_asset_id"], unique=False
    )
    op.create_foreign_key(
        None, "node", "primary_asset", ["primary_asset_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "autodoc_status_history",
        sa.Column("source_version_node_id", sa.Uuid(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "autodoc_status_history",
        "version_node",
        ["source_version_node_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "v2_autodoc_status_history_page_node_id_fkey",
        "autodoc_status_history",
        type_="foreignkey",
    )
    op.alter_column(
        "autodoc_status_history",
        "page_node_id",
        nullable=True,
        existing_type=sa.UUID(),
    )
    op.create_foreign_key(
        None,
        "autodoc_status_history",
        "node",
        ["page_node_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "runtime_llm_session",
        sa.Column("source_version_node_ids_str", sa.String(), nullable=True),
    )
    op.add_column(
        "runtime_llm_session",
        sa.Column("page_version_node_id", sa.Uuid(), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runtime_llm_session", "source_version_node_ids_str")
    op.drop_column("runtime_llm_session", "page_version_node_id")
    op.drop_constraint(
        "autodoc_status_history_page_node_id_fkey",
        "autodoc_status_history",
        type_="foreignkey",
    )
    # op.alter_column(
    #     "autodoc_status_history",
    #     "page_node_id",
    #     existing_type=sa.UUID(),
    #     nullable=False
    # )
    op.create_foreign_key(
        "v2_autodoc_status_history_page_node_id_fkey",
        "autodoc_status_history",
        "node",
        ["page_node_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_constraint(
        "autodoc_status_history_source_version_node_id_fkey",
        "autodoc_status_history",
        type_="foreignkey",
    )
    op.drop_column("autodoc_status_history", "source_version_node_id")
    op.drop_constraint("node_primary_asset_id_fkey", "node", type_="foreignkey")
    op.drop_index(op.f("ix_node_primary_asset_id"), table_name="node")
    op.create_index(
        "ix_version_id_relative_path",
        "node",
        ["version_id", "relative_path"],
        unique=True,
    )
    op.drop_column("node", "primary_asset_id")
    op.drop_column("node", "source_hash")
    op.drop_constraint(
        "document_source_page_node_id_fkey", "document_source", type_="foreignkey"
    )
    op.drop_constraint(
        "document_source_source_node_id_fkey", "document_source", type_="foreignkey"
    )
    op.drop_constraint(
        "document_source_page_version_node_id_fkey",
        "document_source",
        type_="foreignkey",
    )
    op.drop_constraint(
        "document_source_source_version_node_id_fkey",
        "document_source",
        type_="foreignkey",
    )
    op.drop_constraint("document_sources_pkey", "document_source", type_="primary")
    op.alter_column(
        "document_source", "page_node_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "document_source", "source_node_id", existing_type=sa.UUID(), nullable=False
    )
    op.create_primary_key(
        "document_sources_pkey", "document_source", ["source_node_id", "page_node_id"]
    )
    op.create_foreign_key(
        "document_sources_source_node_id_fkey",
        "document_source",
        "node",
        ["source_node_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "document_sources_page_node_id_fkey",
        "document_source",
        "node",
        ["page_node_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # op.create_index('ix_document_source_source_node_id', 'document_source', ['source_node_id'], unique=False)
    # op.create_index('ix_document_source_page_node_id', 'document_source', ['page_node_id'], unique=False)
    op.drop_column("document_source", "page_version_node_id")
    op.drop_column("document_source", "source_version_node_id")
    op.drop_column("document_source", "id")
    op.drop_index(op.f("ix_version_node_version_id"), table_name="version_node")
    op.drop_index(op.f("ix_version_node_relative_path"), table_name="version_node")
    op.drop_index(op.f("ix_version_node_depth"), table_name="version_node")
    op.drop_table("version_node")
    # ### end Alembic commands ###
