"""add_about_you_survey

Revision ID: 0f0a0b0c0d0e
Revises: a7423f274520
Create Date: 2025-08-28 12:00:00.000000

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0f0a0b0c0d0e"
down_revision = "a7423f274520"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "about_you_survey",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skipped", sa.Boolean(), nullable=False),
        sa.Column("plans_for_driver", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("team_size", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("type_of_work", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "type_of_work_other", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_about_you_survey_org_user"
        ),
    )
    op.create_index(
        op.f("ix_about_you_survey_organization_id"),
        "about_you_survey",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_about_you_survey_user_id"),
        "about_you_survey",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_about_you_survey_user_id"), table_name="about_you_survey")
    op.drop_index(
        op.f("ix_about_you_survey_organization_id"), table_name="about_you_survey"
    )
    op.drop_table("about_you_survey")
    # ### end Alembic commands ###
