"""Create AutoDocStatusHistory

Revision ID: c852fcd10a2f
Revises: bf5f2636af5e
Create Date: 2025-04-07 17:42:30.984206

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "c852fcd10a2f"
down_revision = "bf5f2636af5e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "v2_autodoc_status_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("page_node_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status_kind",
            sa.Enum(
                "RETRIEVING_SOURCES",
                "EVALUATING_SECTIONS",
                "EVALUATING_SOURCES",
                "GENERATING_SECTION_DRAFTS",
                "OPTIMIZING_SECTION_STRUCTURE",
                "ASSEMBLING_FINAL_DOCUMENT",
                "COPY_EDITING",
                "GENERATION_COMPLETE",
                "GENERATION_ERROR",
                name="autodocstatusmessagekind",
            ),
            nullable=False,
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("call_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["page_node_id"], ["v2_node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_v2_autodoc_status_history_page_node_id"),
        "v2_autodoc_status_history",
        ["page_node_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_v2_autodoc_status_history_page_node_id"),
        table_name="v2_autodoc_status_history",
    )
    op.drop_table("v2_autodoc_status_history")
    # ### end Alembic commands ###
