"""cleanup models

Revision ID: d28421c6e47b
Revises: e07bf18dd991
Create Date: 2025-01-17 10:39:46.798705

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d28421c6e47b"
down_revision = "e07bf18dd991"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index("ix_codebases_workspace_id", table_name="codebases")
    op.drop_index("ix_derived_contents_codebase_id", table_name="derived_contents")
    op.drop_index("ix_derived_contents_content_name", table_name="derived_contents")
    op.drop_index("ix_derived_contents_content_type_id", table_name="derived_contents")
    op.drop_index(
        "ix_derived_contents_source_content_id", table_name="derived_contents"
    )
    op.drop_index("ix_derived_contents_workspace_id", table_name="derived_contents")
    op.drop_constraint(
        "document_sources_source_id_fkey", "document_sources", type_="foreignkey"
    )
    op.drop_constraint(
        "document_sources_document_id_fkey", "document_sources", type_="foreignkey"
    )

    op.drop_constraint(
        "inspectorrun_version_id_fkey", "inspectorrun", type_="foreignkey"
    )
    op.drop_constraint("codebases_workspace_id_fkey", "codebases", type_="foreignkey")
    op.drop_column("runtimelogagentinstance", "codebase_id")
    op.drop_column("runtimelogagentinstance", "workspace_id")
    op.drop_index("ix_tag_type", table_name="tags")
    op.create_index(op.f("ix_tags_type"), "tags", ["type"], unique=False)
    op.drop_column("derived_contents", "codebase_id")
    op.drop_column("derived_contents", "status")
    op.drop_column("derived_contents", "workspace_id")
    op.drop_column("document_sources", "document_id")
    op.drop_column("document_sources", "include")
    op.drop_column("document_sources", "source_id")
    op.drop_table("workspaces")
    op.drop_table("codebases")
    op.drop_table("inspection_versions")
    op.drop_table("tags_contents")
    op.drop_table("derived_content_types")
    # ### end Alembic commands ###

    op.create_foreign_key(
        None, "inspectorrun", "v2_version", ["version_id"], ["id"], ondelete="SET NULL"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "derived_content_types",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "type_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="derived_content_types_pkey"),
        sa.UniqueConstraint("type_name", name="derived_content_types_type_name_key"),
    )
    op.create_table(
        "tags_contents",
        sa.Column("tag_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("content_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("include", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["derived_contents.id"],
            name="tags_contents_content_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name="tags_contents_tag_id_fkey"
        ),
        sa.PrimaryKeyConstraint("tag_id", "content_id", name="tags_contents_pkey"),
    )
    op.create_table(
        "inspection_versions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("display_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("previous_version_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="inspection_versions_pkey"),
    )
    op.create_table(
        "codebases",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("workspace_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "codebase_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "processing",
                "processing-complete",
                "processing-error",
                "codebase-rejected",
                name="enum_codebase_status",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("storage_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("resource_root", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("creator_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name="codebases_workspace_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="codebases_pkey"),
        sa.UniqueConstraint(
            "workspace_id", "codebase_name", name="uq_workspace_id_codebase_name"
        ),
    )

    op.create_table(
        "workspaces",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "display_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("organization_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="workspaces_pkey"),
    )
    op.create_index(
        "ix_codebases_workspace_id", "codebases", ["workspace_id"], unique=False
    )

    op.drop_index(op.f("ix_tags_type"), table_name="tags")
    op.create_index("ix_tag_type", "tags", ["type"], unique=False)
    op.add_column(
        "runtimelogagentinstance",
        sa.Column("workspace_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "runtimelogagentinstance",
        sa.Column("codebase_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "inspectorrun", type_="foreignkey")
    op.create_foreign_key(
        "inspectorrun_version_id_fkey",
        "inspectorrun",
        "v2_version",
        ["version_id"],
        ["id"],
    )
    op.add_column(
        "document_sources",
        sa.Column("source_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "document_sources",
        sa.Column("include", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "document_sources",
        sa.Column("document_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "document_sources_document_id_fkey",
        "document_sources",
        "derived_contents",
        ["document_id"],
        ["id"],
    )
    op.create_foreign_key(
        "document_sources_source_id_fkey",
        "document_sources",
        "derived_contents",
        ["source_id"],
        ["id"],
    )
    op.add_column(
        "derived_contents",
        sa.Column("workspace_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "derived_contents",
        sa.Column(
            "status",
            postgresql.ENUM(
                "generating",
                "generation-complete",
                "generation-error",
                name="enum_derived_content_status",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "derived_contents",
        sa.Column("codebase_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_derived_contents_workspace_id",
        "derived_contents",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_derived_contents_source_content_id",
        "derived_contents",
        ["source_content_id"],
        unique=False,
    )
    op.create_index(
        "ix_derived_contents_content_type_id",
        "derived_contents",
        ["content_type_id"],
        unique=False,
    )
    op.create_index(
        "ix_derived_contents_content_name",
        "derived_contents",
        ["content_name"],
        unique=False,
    )
    op.create_index(
        "ix_derived_contents_codebase_id",
        "derived_contents",
        ["codebase_id"],
        unique=False,
    )
