"""add subscription types

Revision ID: eaf9d551df52
Revises: 0f0a0b0c0d0e
Create Date: 2025-09-04 11:41:36.626839

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "eaf9d551df52"
down_revision = "0f0a0b0c0d0e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE plantype ADD VALUE 'FREE'")
    op.execute("ALTER TYPE billingfrequency ADD VALUE 'NEVER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
