"""add onboarding checklist table

Revision ID: 20250909_add_onboarding_checklist
Revises: eaf9d551df52
Create Date: 2025-09-09 12:00:00.000000

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "20250909_add_checklist"
down_revision = "eaf9d551df52"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_checklist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "connect_codebase_completed_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "generate_codebase_completed_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("setup_mcp_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("setup_mcp_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "enable_export_completed_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "generate_autodoc_completed_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "invite_teammate_completed_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("checklist_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_onboarding_checklist_org_user"
        ),
    )
    op.create_index(
        op.f("ix_onboarding_checklist_organization_id"),
        "onboarding_checklist",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_onboarding_checklist_user_id"),
        "onboarding_checklist",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_onboarding_checklist_user_id"), table_name="onboarding_checklist"
    )
    op.drop_index(
        op.f("ix_onboarding_checklist_organization_id"),
        table_name="onboarding_checklist",
    )
    op.drop_table("onboarding_checklist")
    # ### end Alembic commands ###
