"""add_vcs_auto_update_policy_to_primary_asset

Revision ID: a7423f274520
Revises: 9eafc58194c2
Create Date: 2025-08-08 15:59:33.147946

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a7423f274520"
down_revision = "9eafc58194c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "v2_primary_asset",
        sa.Column("vcs_auto_update_policy", sa.String(), nullable=True),
    )

    # Set default values for existing records
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE v2_primary_asset
            SET vcs_auto_update_policy = 'AFTER_EVERY_COMMIT'
            WHERE kind = 'CODEBASE' AND provider != 'USER' AND vcs_auto_update_policy IS NULL
        """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("v2_primary_asset", "vcs_auto_update_policy")
    # ### end Alembic commands ###
