"""Add enums for connection

Revision ID: e636d17e65dd
Revises: 3b2cb97a373b
Create Date: 2025-02-11 10:31:34.764020

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "e636d17e65dd"
down_revision = "3b2cb97a373b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TYPE versionstatus ADD VALUE 'CONNECTING'")
    op.execute("ALTER TYPE versionstatus ADD VALUE 'CONNECTION_FAILED'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
