"""content_kind storage=str, validation on init

Revision ID: 950be3322d45
Revises: 22ea847b05a5
Create Date: 2025-01-08 09:43:23.836662

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "950be3322d45"
down_revision = "22ea847b05a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "derived_contents",
        "content_kind",
        existing_type=postgresql.ENUM(
            "pdf-visual-summary",
            "pdf-text-summary",
            "pdf-image-summary",
            "pdf-extracted-text",
            "pdf-extracted-table",
            "template",
            "short_paragraph_description",
            "terse_sentence_description",
            "long_description",
            "quick_start_entry",
            "quick_start_getting_started",
            "quick_start_dependencies",
            "quick_start_use",
            "architecture_diagram",
            "chunk_descriptions",
            "application_note",
            "short_sentence_description",
            "symbol",
            "pdf_summary",
            "codebase",
            "codebase-directory",
            "codebase-file",
            "supplemental-document",
            "TOP_LEVEL_SHORT_SENTENCE",
            "TOP_LEVEL_SHORT_PARAGRAPH",
            "TOP_LEVEL_TERSE_SENTENCE",
            "TOP_LEVEL_LONG_DESCRIPTION",
            name="contentkind",
        ),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "derived_contents",
        "content_kind",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "pdf-visual-summary",
            "pdf-text-summary",
            "pdf-image-summary",
            "pdf-extracted-text",
            "pdf-extracted-table",
            "template",
            "short_paragraph_description",
            "terse_sentence_description",
            "long_description",
            "quick_start_entry",
            "quick_start_getting_started",
            "quick_start_dependencies",
            "quick_start_use",
            "architecture_diagram",
            "chunk_descriptions",
            "application_note",
            "short_sentence_description",
            "symbol",
            "pdf_summary",
            "codebase",
            "codebase-directory",
            "codebase-file",
            "supplemental-document",
            "TOP_LEVEL_SHORT_SENTENCE",
            "TOP_LEVEL_SHORT_PARAGRAPH",
            "TOP_LEVEL_TERSE_SENTENCE",
            "TOP_LEVEL_LONG_DESCRIPTION",
            name="contentkind",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
