"""migrate documentsource

Revision ID: 7478d83c8205
Revises: 6eef6af4e337
Create Date: 2025-01-03 16:34:35.270757

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7478d83c8205"
down_revision = "6eef6af4e337"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns for the compound primary key
    op.add_column(
        "document_sources", sa.Column("source_node_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "document_sources", sa.Column("page_node_id", sa.Uuid(), nullable=True)
    )

    # Update the new columns with appropriate values
    op.execute("""
    UPDATE document_sources
    SET page_node_id = derived_contents.node_id
    FROM derived_contents
    WHERE document_sources.document_id = derived_contents.id;
    """)

    op.execute("""
    UPDATE document_sources
    SET source_node_id = derived_contents.node_id
    FROM derived_contents
    WHERE document_sources.source_id = derived_contents.id;
    """)

    op.execute("""
    UPDATE document_sources
    SET source_node_id = n.id
    FROM derived_contents dc
    LEFT JOIN v2_node n ON n.relative_path = CONCAT(dc.relative_path, '/')
    WHERE document_sources.source_node_id IS NULL
    AND document_sources.source_id = dc.id
    AND dc.content_kind = 'codebase';
    """)

    # Create foreign keys for the new columns
    op.create_foreign_key(None, "document_sources", "v2_node", ["page_node_id"], ["id"])
    op.create_foreign_key(
        None, "document_sources", "v2_node", ["source_node_id"], ["id"]
    )

    # # Alter existing columns to be nullable
    # op.alter_column(
    #     "document_sources", "document_id", existing_type=sa.UUID(), nullable=True
    # )
    # op.alter_column(
    #     "document_sources", "include", existing_type=sa.BOOLEAN(), nullable=True
    # )
    # op.alter_column(
    #     "document_sources", "source_id", existing_type=sa.UUID(), nullable=True
    # )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, "document_sources", type_="foreignkey")
    # op.drop_constraint(None, "document_sources", type_="foreignkey")
    op.drop_column("document_sources", "page_node_id")
    op.drop_column("document_sources", "source_node_id")
    # ### end Alembic commands ###
