"""persistent message_history

Revision ID: bf5f2636af5e
Revises: 47fbcf862323
Create Date: 2025-03-13 13:19:12.452053

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bf5f2636af5e"
down_revision = "47fbcf862323"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "v2_runtime_llm_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "source_node_ids_str", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("page_node_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_v2_runtime_llm_session_organization_id"),
        "v2_runtime_llm_session",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_runtime_llm_session_user_id"),
        "v2_runtime_llm_session",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "v2_runtime_llm_message_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("llm_session_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["llm_session_id"], ["v2_runtime_llm_session.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_v2_runtime_llm_message_history_llm_session_id"),
        "v2_runtime_llm_message_history",
        ["llm_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_runtime_llm_message_history_pipeline_kind"),
        "v2_runtime_llm_message_history",
        ["pipeline_kind"],
        unique=False,
    )
    op.create_table(
        "v2_runtime_llm_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_history_id", sa.Uuid(), nullable=False),
        sa.Column(
            "llm_message_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "llm_message_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_history_id"],
            ["v2_runtime_llm_message_history.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_v2_runtime_llm_messages_message_history_id"),
        "v2_runtime_llm_messages",
        ["message_history_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_v2_runtime_llm_messages_message_history_id"),
        table_name="v2_runtime_llm_messages",
    )
    op.drop_table("v2_runtime_llm_messages")
    op.drop_index(
        op.f("ix_v2_runtime_llm_message_history_pipeline_kind"),
        table_name="v2_runtime_llm_message_history",
    )
    op.drop_index(
        op.f("ix_v2_runtime_llm_message_history_llm_session_id"),
        table_name="v2_runtime_llm_message_history",
    )
    op.drop_table("v2_runtime_llm_message_history")
    op.drop_index(
        op.f("ix_v2_runtime_llm_session_user_id"), table_name="v2_runtime_llm_session"
    )
    op.drop_index(
        op.f("ix_v2_runtime_llm_session_organization_id"),
        table_name="v2_runtime_llm_session",
    )
    op.drop_table("v2_runtime_llm_session")
    # ### end Alembic commands ###
