"""add pa and node parentage indexes

Revision ID: a8b7cafaa51f
Revises: 4ec484ef0f5b
Create Date: 2025-02-10 16:48:32.713019

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a8b7cafaa51f"
down_revision = "4ec484ef0f5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_node_version_id_relative_path_length",
        "v2_node",
        ["version_id", sa.text("length('relative_path')")],
        unique=False,
    )
    op.create_index(
        "ix_node_version_id_relative_path_pattern_ops",
        "v2_node",
        ["version_id"],
        unique=False,
        postgresql_ops={"relative_path": "text_pattern_ops"},
    )
    op.create_index(
        op.f("ix_v2_node_version_id"), "v2_node", ["version_id"], unique=False
    )
    op.create_index(
        op.f("ix_v2_primary_asset_display_name"),
        "v2_primary_asset",
        ["display_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_primary_asset_kind"), "v2_primary_asset", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_v2_primary_asset_organization_id"),
        "v2_primary_asset",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_primary_asset_tag_primary_asset_id"),
        "v2_primary_asset_tag",
        ["primary_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_primary_asset_tag_tag_id"),
        "v2_primary_asset_tag",
        ["tag_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_version_primary_asset_id"),
        "v2_version",
        ["primary_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_version_updated_at"), "v2_version", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_v2_version_updated_at"), table_name="v2_version")
    op.drop_index(op.f("ix_v2_version_primary_asset_id"), table_name="v2_version")
    op.drop_index(
        op.f("ix_v2_primary_asset_tag_tag_id"), table_name="v2_primary_asset_tag"
    )
    op.drop_index(
        op.f("ix_v2_primary_asset_tag_primary_asset_id"),
        table_name="v2_primary_asset_tag",
    )
    op.drop_index(
        op.f("ix_v2_primary_asset_organization_id"), table_name="v2_primary_asset"
    )
    op.drop_index(op.f("ix_v2_primary_asset_kind"), table_name="v2_primary_asset")
    op.drop_index(
        op.f("ix_v2_primary_asset_display_name"), table_name="v2_primary_asset"
    )
    op.drop_index(op.f("ix_v2_node_version_id"), table_name="v2_node")
    op.drop_index(
        "ix_node_version_id_relative_path_pattern_ops",
        table_name="v2_node",
        postgresql_ops={"relative_path": "text_pattern_ops"},
    )
    op.drop_index("idx_node_version_id_relative_path_length", table_name="v2_node")
    # ### end Alembic commands ###
