"""update git_provider_app_install table

Revision ID: 2c5d9d6cbdb5
Revises: a8b7cafaa51f
Create Date: 2025-02-18 14:42:28.083064

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2c5d9d6cbdb5"
down_revision = "a8b7cafaa51f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "git_provider_apps", "scopes", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "git_provider_apps", "redirect_uri", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "git_provider_apps", "client_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.add_column(
        "git_provider_app_installations",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "git_provider_app_installations",
        "user_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "git_provider_app_installations",
        "user_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("git_provider_app_installations", "metadata")
    op.alter_column(
        "git_provider_apps", "client_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "git_provider_apps", "redirect_uri", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "git_provider_apps", "scopes", existing_type=sa.VARCHAR(), nullable=False
    )

    # ### end Alembic commands ###
