"""Drops display_name from version

Revision ID: 92911ce2fccd
Revises: e92af25eccc5
Create Date: 2025-07-16 13:50:12.261662

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "92911ce2fccd"
down_revision = "e92af25eccc5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_v2_version_primary_asset_id_display_name", table_name="v2_version"
    )
    op.create_index(
        "ix_v2_version_primary_asset_id_vcs_hash",
        "v2_version",
        ["primary_asset_id", "vcs_hash"],
        unique=True,
    )
    op.drop_column("v2_version", "display_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
