"""Adds NOT_STARTED to autodoc status

Revision ID: 61e839b3f9cd
Revises: 21e1da60676a
Create Date: 2025-04-10 16:52:37.614700

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "61e839b3f9cd"
down_revision = "21e1da60676a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("ALTER TYPE autodocstatusmessagekind ADD VALUE 'NOT_STARTED'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("ALTER TYPE autodocstatusmessagekind DROP VALUE 'NOT_STARTED'")
