"""dont need metadata index

Revision ID: c658bca65e0c
Revises: d28421c6e47b
Create Date: 2025-01-17 13:24:24.403036

"""

# revision identifiers, used by Alembic.
revision = "c658bca65e0c"
down_revision = "d28421c6e47b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(
    #     "derived_contents_metadata_idx",
    #     table_name="derived_contents",
    #     postgresql_using="gin",
    # )
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(
    #     "derived_contents_metadata_idx",
    #     "derived_contents",
    #     ["metadata"],
    #     unique=False,
    #     postgresql_using="gin",
    # )
    # ### end Alembic commands ###
    pass
