"""make vcs_hash nulls not unique for primary_asset_id-vcs_hash unique constraint

Revision ID: d3db21ab0782
Revises: 92911ce2fccd
Create Date: 2025-07-17 12:16:18.046912

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d3db21ab0782"
down_revision = "92911ce2fccd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_v2_version_primary_asset_id_vcs_hash", table_name="v2_version")
    op.create_unique_constraint(
        "ix_v2_version_primary_asset_id_vcs_hash",
        "v2_version",
        ["primary_asset_id", "vcs_hash"],
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ix_v2_version_primary_asset_id_vcs_hash", "v2_version", type_="unique"
    )
    op.create_index(
        "ix_v2_version_primary_asset_id_vcs_hash",
        "v2_version",
        ["primary_asset_id", "vcs_hash"],
        unique=True,
    )
    # ### end Alembic commands ###
